# Site wide configuration

title: Become Great at R
locale: en_US
description: 
logo: site-logo.png
search: true
url: https://masterr.org


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge # pygments
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Guangming Lang
  avatar: gmlang1.jpg
  email: gmlang@cabaceo.com
  disqus-shortname: masterrorg
  twitter: #username
  facebook: #username
  github: #username
  stackexchange: #https://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics: UA-57697212-1
    verify:
    ad-client: ca-pub-8728996999064894
    ad-slot: 7055819766
  bing-verify: "F608C5B05384F7B0200AC62F5BB60411"